# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: sky's site
email: skaaiedev@gmail.com
name: &name sky
description: >- # this means to ignore newlines until "baseurl:"
  My site that I'm probably just gonna use for changelogs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sky675.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: skaaie
github_username:  sky675

author:
  name: *name
  avatar: "/assets/images/modelv3_shot_t5_edit3_crop.png"
  bio: solo game dev trying her best. contact email can be found on youtube
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sky675"
    - label: "itch.io"
      icon: "fab fa-fw fa-itch-io"
      url: "https://sky675.itch.io/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCnqczZEtybB_mx7Jz_797uw"

minimal_mistakes_skin: neon

permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
#default is 200
words_per_minute: 150

#itch, youtube, github
footer:
  links:
    - label: "itch.io"
      icon: "fab fa-fw fa-itch-io"
      url: "https://sky675.itch.io/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCnqczZEtybB_mx7Jz_797uw"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/sky675"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/ub2DQSS2xE"
    - label: "Categories"
      url: "/categories/"
    - label: "Tags"
      url: "/tags/"

collections:
  changelogs:
    output: true
    permalink: /:collection/:path/

defaults:
  # _changelogs
  - scope:
      path: ""
      type: changelogs
    values:
      layout: single
      read_time: true
      toc: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      header:
        overlay_image: assets/images/event_header_generic1.png
        show_overlay_excerpt: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      title: " "
      header:
        overlay_image: /assets/images/event_header_generic1.png
        no-bottom: true

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.26.2
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
